### PR TITLE
Version 1.0.6

### PR DESCRIPTION
**Pull request by Lan-Hekary**
* Added a new buffer W/R handlers to increase speed in SPIFFS and SD Cards
* Added EDB_SPIFFS_Optimized example
* Added EDB_SDCARD_Optimized example
* Fixed a Warning about typedef in Compilation

The library is back compatible, so there is no need to change the Magic
I tested new features on ESP8266 chip and the speed of the Operations increased by a factor of x10

### CODE REVIEW

**Comment by capedra** [comment]
Hello, did you test it using ESP's EEPROM? the Wemos D1 Mini Pro keeps doing wdt resets as soon as I create the database on EEPROM. the same thing happens with 1.0.4.

**Comment by Lan-Hekary** [comment]
Hi @capedra ,
Sadly, NO I did not test it on EEPROM but if you could open an Issue and and post some more details like the exact version on ESP8266 Core you're using I'd be able to help
also try to put the code that causes the wdt resets ..

**Comment by Lan-Hekary** [comment]
I was exploring the others forks for the library and found a fork for @DedeHai at 
https://github.com/fablabwinti/EDB/commit/87f312cde7069318f7836221f025cd095856bd4e

this this the same optimization but I maintained compatibility :D

**Comment by DedeHai** [comment]
Quite an elegant solution @Lan-Hekary, exactly what I wanted to do but I could not figure out how to overload the constructor properly so I gave up and had to brake compatibility in my branch. 
Thanks for sharing.

**Pull request merged**
